### ISSUE TITLE
Feedback Sprint 1 Datadashboard 

### ISSUE THREAD

**Issue by nerdale** [NancyyM/cdmx-2018-06-bc-core-am-data-dashboard#18]
Hola @NancyyM y Compañera
He estado revisando el proyecto y tengo algunos comentarios:

1. @NancyyM debes agregar como colaboradora a **esmerivero**, es extremadamente necesario pues los issues van guiados hacia ambas.

2. Que pasó con el deploy a Github Pages? era uno de los requisitos para el demo del sprint 1

3. Que pasó con el tema de UX? no lo encontré en el repositorio, no hay información sobre la investigación y descubrimiento de usuarios, sintesis, sketching de baja y alta fidelidad.

4. Me causa curiosidad todo el código que hay en **main.js** como lo hicieron? si en ningún archivo están utilizando ni xhr ni fetch para llamar al json con la data, o al menos yo no lo encontré.

5. Tira un error en el archivo json, ojo con eso, revisen la modificación que le hicieron.

6. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

7. No descuiden el trabajo colaborativo en github, debe ser equitativo en cuanto a cantidad/calidad de commits.

Vamos con power!! son capaces de mucho, muestren en este proyecto lo grandes que pueden ser en el desarrollo :rocket:

**Comment by esmerivero** [comment]
@nerdale Ok, enteradas.
Muchas gracias!

**Comment by nerdale** [comment]
Daré por cerrado el issue :smile: 
:rocket:
